### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by blowsie** [tristanguigue/angular-dynamic-layout#48]
Hi,

Your readme states: BETA, not production ready.
I'm just wondering, what specially is missing / needs to be done to get this project production ready?

Thanks

**Comment by tristanguigue** [comment]
Hi there, thanks for your interest, I developed this project as a pure AngularJS alternative to integrating the jQuery Isotope library into the platform of the company I was working for. Eventually, the platform moved away from AngularJS to React and this project never made it into production. Since it hasn't be moved into production it is not as robust and thoroughly tested as it should be, hence the warning.

On a side note, I am not currently working on this project and do not plan to be in the future so if anyone want to take over and continue the development I am happy to add them as administrators.

**Comment by blowsie** [comment]
@tristanguigue Thanks, I'll have a trial with the project and consider If it is something I could use in production at my place of work. If so, I may well look at making improvements and tests. Thanks
